services:
  - type: web
    name: academia-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        sync: false
      - key: Jwt__SigningKey
        sync: false
      - key: Jwt__Issuer
        value: ApiAcademia
      - key: Jwt__Audience
        value: ApiAcademia.Client
      - key: Jwt__ExpiresMinutes
        value: "60"
      - key: Auth__RequireEmailConfirmation
        value: "false"
      - key: Auth__RequireTwoFactor
        value: "false"
      - key: MercadoPago__CurrencyId
        value: BRL
      - key: MercadoPago__UseSandbox
        value: "false"
      - key: MercadoPago__AccessToken
        sync: false
      - key: MercadoPago__NotificationUrl
        sync: false
      - key: Cors__AllowedOrigins__0
        sync: false
      - key: Cors__AllowedVercelHostSuffix
        value: .vercel.app
      - key: SeedAdmin__Password
        sync: false
      - key: SeedAdmin__Email
        value: admin@pulsefit.com
